[tool.robotidy]
src = ["tests"]
overwrite = false
diff = true
spacecount = 4
continuation-indent = 4
transform = [
    "DiscardEmptySections:allow_only_comments=True",
    "SplitTooLongLine",
    "NormalizeSeparators",
]
configure = ["SplitTooLongLine:split_on_every_arg=False"]
