[qase]
qase_testops_api_token=b45e559f1709f1c61454cd43caacef762a27b278f73f79b059ed7a1d9a12bafc
qase_testops_project=CDS
qase_testops_run_title=Robot Framework Test
qase_debug=True
qase_testops_complete_run=True
qase_mode=testops
