name: Run Example tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  QASE_TESTOPS_PROJECT: ${{ vars.QASE_TESTOPS_PROJECT }}
  QASE_TESTOPS_RUN_COMPLETE: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Setup Chromedriver
        uses: SeleniumHQ/setup-selenium@v1
        with:
          browser: chrome
          version: latest

      - name: Verify Chrome and Chromedriver Versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Get run title
        id: set_title
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          echo "QASE_TESTOPS_RUN_TITLE=qase-pytest@$BRANCH_NAME: $COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Run Pytest tests
        env:
          QASE_MODE: "testops"
        run: |
          robot --listener qase.robotframework.Listener tests/examples/*.robot
