name: Run Example tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  QASE_TESTOPS_PROJECT: ${{ vars.QASE_TESTOPS_PROJECT }}
  QASE_TESTOPS_RUN_COMPLETE: true

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 'Setup Chrome and chromedriver'
        runs:
          using: "composite"
          steps:
            - run: |
                wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
                echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
                sudo apt-get update -qqy
                sudo apt-get -qqy install google-chrome-stable
                CHROME_VERSION=$(google-chrome-stable --version)
                CHROME_FULL_VERSION=${CHROME_VERSION%%.*}
                CHROME_MAJOR_VERSION=${CHROME_FULL_VERSION//[!0-9]}
                sudo rm /etc/apt/sources.list.d/google-chrome.list
                export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
                curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
                unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
                export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
                curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
                unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
                chromedriver -version
              shell: bash

      - name: Verify Chrome and Chromedriver Versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Get run title
        id: set_title
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          echo "QASE_TESTOPS_RUN_TITLE=qase-pytest@$BRANCH_NAME: $COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Run Robot tests
        env:
          QASE_MODE: "testops"
        run: |
          robot --listener qase.robotframework.Listener tests/examples/*.robot
